on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: NuGet/setup-nuget@v2.0.0
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - run: |
          cd NikYo.UpdatableProperty
          dotnet pack -o .
          nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
